### ISSUE TITLE
Add custom classes to the dialog

### ISSUE THREAD

**Issue by Jopie01** [onechiporenko/ember-paper-modals-manager#2]
I want to add a custom class to the main-dialog (md-dialog), but I don't know how. Is it possible to add these through the option object?

**Comment by onechiporenko** [comment]
Hi, @Jopie01. No, it's not possible to do this via `options`. You can try to override existing templates and add it there. 
I'll think about adding this feature/

**Comment by Jopie01** [comment]
It's not that hard, I added in the templates of this addon `class=options.cssClass` to the `paper-dialog`. Then in my own code I added e.g. `cssClass='flex verywide`. That's all. The classes are added to the `<md-dialog>`. So no coding needed.
