### ISSUE TITLE
Default layouts not working

### ISSUE THREAD

**Issue by betocantu93** [onechiporenko/ember-paper-modals-manager#4]
Hello, great addon! way simplier than how I handled this.

Just one question, why the layouts are not exported with the components? I can't get them to show (not sure if its because I'm using ember-engines)...

But I had to extend all of the components to place the layout, while also copying all of the hbs's.

I saw a commit that layouts were removed, but I'm not sure why (in the internal addon)

Thanks in advance.

**Comment by onechiporenko** [comment]
Hi, @betocantu93. Sorry for so late response. 
I've checked `modals-manager` with latest `ember-paper` on the new clear application using `ember-cli@3.9.0` and it works as it should. I'm not familiar with ember-engines, so I can't test it correctly. I'' appreciate if you can provide a stand-alone repo with reproduction.
