### ISSUE TITLE
Issue with Import

### ISSUE THREAD

**Issue by wukongrita** [onechiporenko/ember-paper-modals-manager#9]
Hi @onechiporenko 

This is a great add on and I've been using it with no problem. Now, I try to convert my App to Ember 3.16 but I got some error on displaying the modal dialog. Here is what it says:

```
Uncaught Error: Could not find module `ember-modals-manager-internal/templates/components/modals-container/alert` imported from `ember-paper-modals-manager/components/modals-container/alert`
```

May be it is also related to this issue:

https://github.com/onechiporenko/ember-bootstrap-modals-manager/issues/12

Any help on this? Thank you...

**Comment by wukongrita** [comment]
If I modify:

`ember-paper-modals-manager/addon/components/modals-container/alert.js`
```
import layout from 'ember-modals-manager-internal/templates/components/modals-container/alert';
```
to
```
import layout from 'ember-modals-manager-internal/templates/components/modals-container';
```
it works!

So, I got to modify all files that contain `.../modals-container/***` to `.../modals-container`

I don't know if this should be like that or not..

**Comment by onechiporenko** [comment]
Hi, @wukongrita. Thanks for reporting. I'm going to check/fix described issue.

**Comment by wukongrita** [comment]
Hi, @onechiporenko .. any update on this? Thanks...
